async function request(path, options = {}) {
  const response = await fetch(path, { credentials: 'same-origin', ...options })
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || '请求失败')
  return response.status === 204 ? null : response.json()
}
export const api = {
  documentLibraries: (keyword = '', status = '') => request(`/api/document-libraries?keyword=${encodeURIComponent(keyword)}${status ? `&status=${encodeURIComponent(status)}` : ''}`),
  createDocumentLibrary: body => request('/api/document-libraries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  sources: (libraryId = '', keyword = '', status = '') => request(libraryId ? `/api/document-libraries/${libraryId}/sources?keyword=${encodeURIComponent(keyword)}${status ? `&status=${status}` : ''}` : `/api/sources?keyword=${encodeURIComponent(keyword)}${status ? `&status=${status}` : ''}`),
  documentTree: libraryId => request(`/api/document-libraries/${libraryId}/tree`),
  documentTemplateBindings: libraryId => request(`/api/document-libraries/${libraryId}/template-bindings`),
  bindDocumentTemplate: (libraryId, knowledge_flow_template_id) => request(`/api/document-libraries/${libraryId}/template-bindings`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ knowledge_flow_template_id }) }),
  bindDocumentTemplates: (libraryId, knowledge_flow_template_ids) => request(`/api/document-libraries/${libraryId}/template-bindings/batch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ knowledge_flow_template_ids }) }),
  unbindDocumentTemplate: (libraryId, templateId) => request(`/api/document-libraries/${libraryId}/template-bindings/${templateId}`, { method: 'DELETE' }),
  processDocumentLibrary: libraryId => request(`/api/document-libraries/${libraryId}/process`, { method: 'POST' }),
  processSelectedDocumentSources: (libraryId, source_ids) => request(`/api/document-libraries/${libraryId}/process-selected`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_ids }) }),
  librarySources: (libraryId, params = {}) => request(`/api/document-libraries/${libraryId}/sources?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined)).toString()}`),
  sourceImportPreflight: (libraryId, entries) => request(`/api/document-libraries/${libraryId}/sources/import-preflight`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ entries }) }),
  importSources: (libraryId, form) => request(`/api/document-libraries/${libraryId}/sources/batch`, { method: 'POST', body: form }),
  uploadSources: (libraryId, form) => request(`/api/document-libraries/${libraryId}/sources/upload`, { method: 'POST', body: form }),
  sourceVersions: sourceId => request(`/api/sources/${sourceId}/versions`),
  replaceSource: (sourceId, form) => request(`/api/sources/${sourceId}/replace`, { method: 'POST', body: form }),
  deleteSource: sourceId => request(`/api/sources/${sourceId}`, { method: 'DELETE' }),
  retrySource: sourceId => request(`/api/sources/${sourceId}/retry`, { method: 'POST' }),
  sourceDetail: (sourceId, versionId = '', flowRunId = '') => request(`/api/sources/${sourceId}/detail?${new URLSearchParams(Object.entries({ version_id: versionId, flow_run_id: flowRunId }).filter(([, value]) => value)).toString()}`),
  sourceDownloadUrl: (sourceId, versionId) => `/api/sources/${sourceId}/versions/${versionId}/download`,
  documentDeletionPreflight: body => request('/api/document-deletions/preflight', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  requestDocumentDeletion: body => request('/api/document-deletions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  retryDocumentDeletion: jobId => request(`/api/document-deletion-jobs/${jobId}/retry`, { method: 'POST' }),
  knowledgeLibraries: type => request(`/api/knowledge-libraries${type ? `?knowledge_type=${type}` : ''}`),
  createKnowledgeLibrary: body => request('/api/knowledge-libraries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  knowledgeLibraryDeleteCheck: libraryId => request(`/api/knowledge-libraries/${libraryId}/delete-check`),
  deleteKnowledgeLibrary: libraryId => request(`/api/knowledge-libraries/${libraryId}`, { method: 'DELETE' }),
  deletionJobs: libraryId => request(`/api/knowledge-libraries/${libraryId}/deletion-jobs`),
  retryDeletion: jobId => request(`/api/knowledge-library-deletion-jobs/${jobId}/retry`, { method: 'POST' }),
  knowledgeItems: libraryId => request(`/api/knowledge-libraries/${libraryId}/items`),
  qaPairs: libraryId => request(`/api/knowledge-libraries/${libraryId}/qa-pairs`),
  graph: libraryId => request(`/api/knowledge-libraries/${libraryId}/graph`),
  graphOverview: libraryId => request(`/api/knowledge-libraries/${libraryId}/graph/overview`),
  changes: libraryId => request(`/api/knowledge-libraries/${libraryId}/changes`),
  vectorStatus: libraryId => request(`/api/knowledge-libraries/${libraryId}/vector-status`),
  knowledgeItemSources: itemId => request(`/api/knowledge-items/${itemId}/sources`),
  graphEntities: (libraryId, q = '') => request(`/api/knowledge-libraries/${libraryId}/graph/entities?q=${encodeURIComponent(q)}`),
  graphEntity: (libraryId, entityId) => request(`/api/knowledge-libraries/${libraryId}/graph/entities/${entityId}`),
  graphNeighbors: (libraryId, entityId, depth = 1) => request(`/api/knowledge-libraries/${libraryId}/graph/entities/${entityId}/neighbors?depth=${depth}`),
  graphEvidence: (libraryId, relationId) => request(`/api/knowledge-libraries/${libraryId}/graph/relations/${relationId}/evidence`),
  knowledgeJobs: () => request('/api/knowledge-jobs'),
  createKnowledgeJob: body => request('/api/knowledge-jobs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  manageKnowledgeJobs: body => request('/api/knowledge-jobs/batch-actions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  knowledgeJobLogs: jobId => request(`/api/knowledge-jobs/${jobId}/logs`),
  knowledgeJobChunkGenerations: (jobId, failedOnly = false) => request(`/api/knowledge-jobs/${jobId}/chunk-generations${failedOnly ? '?failed_only=true' : ''}`),
  knowledgeTypes: () => request('/api/developer/knowledge-types'),
  createKnowledgeType: body => request('/api/developer/knowledge-types', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  reviseKnowledgeType: (id, body) => request(`/api/developer/knowledge-types/${id}/revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateKnowledgeType: id => request(`/api/developer/knowledge-types/${id}/validate`, { method: 'POST' }),
  publishKnowledgeType: id => request(`/api/developer/knowledge-types/${id}/publish`, { method: 'POST' }),
  standardPipelines: () => request('/api/developer/standard-pipelines'),
  operatorCatalog: (params = {}) => request(`/api/developer/operator-catalog?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined)).toString()}`),
  operatorCatalogFacets: () => request('/api/developer/operator-catalog/facets'),
  operatorDetail: code => request(`/api/developer/operator-catalog/${encodeURIComponent(code)}`),
  promptTemplates: () => request('/api/developer/prompt-templates'),
  qualityProfiles: () => request('/api/developer/quality-profiles'),
  flowSubgraphs: () => request('/api/developer/flow-subgraphs'),
  flowSubgraphRevision: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}`),
  copyFlowSubgraphDraft: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/copy`, { method: 'POST' }),
  updateFlowSubgraphDraft: (id, revision, body) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateFlowSubgraphDraft: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/validate`, { method: 'POST' }),
  publishFlowSubgraphDraft: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/publish`, { method: 'POST' }),
  flowTemplates: () => request('/api/developer/knowledge-flow-templates'),
  createFlowTemplate: body => request('/api/developer/knowledge-flow-templates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  updateFlowTemplate: (id, body) => request(`/api/developer/knowledge-flow-templates/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  archiveFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}`, { method: 'DELETE' }),
  defaultFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}/set-default`, { method: 'POST' }),
  validateFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}/validate`, { method: 'POST' }),
  publishFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}/publish`, { method: 'POST' }),
  sampleFlowTemplate: (id, sample_id) => request(`/api/developer/knowledge-flow-templates/${id}/sample-run`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sample_id }) }),
  executionSnapshot: id => request(`/api/developer/execution-snapshots/${id}`),
  flowRuns: () => request('/api/developer/flow-runs'),
  flowRun: id => request(`/api/developer/flow-runs/${id}`),
  flowRunCapabilities: () => request('/api/developer/flow-runs/capabilities'),
  flowRunEvents: (id, cursor = 0, limit = 100) => request(`/api/developer/flow-runs/${id}/events?after=${cursor}&limit=${limit}`),
  createDerivedRun: (id, body) => request(`/api/developer/flow-runs/${id}/derived-runs`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  cancelFlowRun: id => request(`/api/developer/flow-runs/${id}/cancel`, { method: 'POST' }),
  persistDerivedParameters: (id, body) => request(`/api/developer/flow-runs/${id}/persist-parameters`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  commitFlowRun: (id, body) => request(`/api/developer/flow-runs/${id}/commit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  artifactDetail: id => request(`/api/developer/artifacts/${id}`),
  artifactContent: (id, offset = 0, limit = 50) => request(`/api/developer/artifacts/${id}/content?offset=${offset}&limit=${limit}`),
  vectorIndexes: () => request('/api/developer/vector-indexes'),
  managedCollections: () => request('/api/developer/managed-collections'),
  reconcileManagedCollection: id => request(`/api/developer/managed-collections/${id}/reconcile`, { method: 'POST' }),
  managedCollectionDeleteCheck: id => request(`/api/developer/managed-collections/${id}/delete-check`),
  deleteManagedCollection: id => request(`/api/developer/managed-collections/${id}`, { method: 'DELETE' }),
  managedCollectionDeletionJobs: id => request(`/api/developer/managed-collections/${id}/deletion-jobs`),
  retryManagedCollectionDeletion: id => request(`/api/developer/managed-collection-deletion-jobs/${id}/retry`, { method: 'POST' }),
  createIndexProfile: body => request('/api/developer/index-profiles', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  reviseIndexProfile: (id, body) => request(`/api/developer/index-profiles/${id}/revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateIndexProfile: id => request(`/api/developer/index-profiles/${id}/validate`, { method: 'POST' }),
  publishIndexProfile: id => request(`/api/developer/index-profiles/${id}/publish`, { method: 'POST' }),
  archiveIndexProfile: id => request(`/api/developer/index-profiles/${id}/archive`, { method: 'POST' }),
  vectorSyncJobs: libraryId => request(`/api/vector-sync-jobs${libraryId ? `?knowledge_library_id=${libraryId}` : ''}`),
  queueVectorSync: libraryId => request(`/api/knowledge-libraries/${libraryId}/vector-sync-jobs`, { method: 'POST' }),
  runVectorSync: jobId => request(`/api/vector-sync-jobs/${jobId}/run`, { method: 'POST' }),
  projects: () => request('/api/projects'),
  createProject: body => request('/api/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  createProjectTask: (projectId, body) => request(`/api/projects/${projectId}/tasks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  putRoute: (taskId, body) => request(`/api/project-tasks/${taskId}/org-routes`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateRouting: projectId => request(`/api/projects/${projectId}/routing/validate`, { method: 'POST' }),
  routingDiff: projectId => request(`/api/projects/${projectId}/routing/diff`),
  publishRouting: projectId => request(`/api/projects/${projectId}/routing/publish`, { method: 'POST' }),
  routeVersions: projectId => request(`/api/projects/${projectId}/routing/versions`),
  routeVersion: (projectId, version) => request(`/api/projects/${projectId}/routing/versions/${version}`),
  rollbackRouting: (projectId, version) => request(`/api/projects/${projectId}/routing/rollback/${version}`, { method: 'POST' }),
}
