export class ApiRequestError extends Error {
  constructor({ method, url, status, requestId, detail, problem = null }) {
    const structured = problem || (detail && typeof detail === 'object' ? detail : null)
    const readable = structured?.message || (typeof detail === 'string' ? detail : structured ? JSON.stringify(structured) : '请求失败')
    const message = `${method} ${url} · HTTP ${status}${requestId ? ` · request_id ${requestId}` : ''} · ${readable}`
    super(message)
    this.name = 'ApiRequestError'; this.method = method; this.url = url; this.status = status
    this.requestId = requestId; this.detail = readable; this.problem = structured
  }
}

export function createClientRequestId(cryptoApi = globalThis.crypto) {
  if (typeof cryptoApi?.randomUUID === 'function') return cryptoApi.randomUUID()

  const bytes = new Uint8Array(16)
  if (typeof cryptoApi?.getRandomValues === 'function') cryptoApi.getRandomValues(bytes)
  else for (let index = 0; index < bytes.length; index += 1) bytes[index] = Math.floor(Math.random() * 256)
  bytes[6] = (bytes[6] & 0x0f) | 0x40
  bytes[8] = (bytes[8] & 0x3f) | 0x80
  const hex = Array.from(bytes, value => value.toString(16).padStart(2, '0')).join('')
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`
}

async function request(path, options = {}) {
  const method = String(options.method || 'GET').toUpperCase()
  const requestId = createClientRequestId()
  const headers = { 'X-Request-ID': requestId, ...(options.headers || {}) }
  const response = await fetch(path, { credentials: 'same-origin', ...options, headers })
  if (!response.ok) {
    const raw = await response.text().catch(() => '')
    let detail = raw, problem = null
    try {
      const parsed = JSON.parse(raw), value = parsed.detail ?? parsed.error ?? parsed
      if (value && typeof value === 'object') { problem = value; detail = value.message || JSON.stringify(value) }
      else detail = String(value || raw)
    } catch (_) {}
    throw new ApiRequestError({ method, url: path, status: response.status, requestId: response.headers.get('X-Request-ID') || requestId, detail, problem })
  }
  return response.status === 204 ? null : response.json()
}

function graphNeighborQuery(depth, filters = {}, confirmLarge = false) {
  const params = new URLSearchParams({ depth: String(depth) })
  for (const value of filters.entityTypes || []) params.append('entity_types', value)
  for (const value of filters.relationTypes || []) params.append('relation_types', value)
  if (confirmLarge) params.set('confirm_large', 'true')
  return params.toString()
}

function json(method, payload) { return { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) } }

export const api = {
  rerankerServings: () => request('/api/reranker-servings'),
  createRerankerServing: body => request('/api/reranker-servings', json('POST', body)),
  patchRerankerServing: (id, body) => request(`/api/reranker-servings/${id}`, json('PATCH', body)),
  testRerankerServing: id => request(`/api/reranker-servings/${id}/test`, { method: 'POST' }),
  defaultRerankerServing: id => request(`/api/reranker-servings/${id}/set-default`, { method: 'POST' }),
  rerankerServingReferences: id => request(`/api/reranker-servings/${id}/references`),
  deleteRerankerServing: id => request(`/api/reranker-servings/${id}`, { method: 'DELETE' }),
  patchDeploymentTask: (id, taskId, body) => request(`/api/projects/${id}/release-tasks/${taskId}`, json('PATCH', body)),
  retrievalDebugOptions: (id, params) => request(`/api/projects/${id}/retrieval-debug/options?${new URLSearchParams(params)}`),
  retrievalDebug: (id, body) => request(`/api/projects/${id}/retrieval-debug`, json('POST', body)),
  retrievalPublicTest: (id, body) => request(`/api/projects/${id}/retrieval-public-test`, json('POST', body)),
  servingCategories: () => request('/api/serving-categories'),
  modelServings: () => request('/api/model-servings'),
  createModelServing: body => request('/api/model-servings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  patchModelServing: (id, body) => request(`/api/model-servings/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  testModelServing: id => request(`/api/model-servings/${id}/test`, { method: 'POST' }),
  defaultModelServing: id => request(`/api/model-servings/${id}/set-default`, { method: 'POST' }),
  modelServingReferences: id => request(`/api/model-servings/${id}/references`),
  deleteModelServing: id => request(`/api/model-servings/${id}`, { method: 'DELETE' }),
  embeddingServings: () => request('/api/embedding-servings'),
  createEmbeddingServing: body => request('/api/embedding-servings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  patchEmbeddingServing: (id, body) => request(`/api/embedding-servings/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  testEmbeddingServing: id => request(`/api/embedding-servings/${id}/test`, { method: 'POST' }),
  defaultEmbeddingServing: id => request(`/api/embedding-servings/${id}/set-default`, { method: 'POST' }),
  embeddingServingReferences: id => request(`/api/embedding-servings/${id}/references`),
  deleteEmbeddingServing: id => request(`/api/embedding-servings/${id}`, { method: 'DELETE' }),
  dashboardOverview: () => request('/api/dashboard/overview'),
  documentLibraries: (keyword = '', status = '') => request(`/api/document-libraries?keyword=${encodeURIComponent(keyword)}${status ? `&status=${encodeURIComponent(status)}` : ''}`),
  createDocumentLibrary: body => request('/api/document-libraries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  sources: (libraryId = '', keyword = '', status = '') => request(libraryId ? `/api/document-libraries/${libraryId}/sources?keyword=${encodeURIComponent(keyword)}${status ? `&status=${status}` : ''}` : `/api/sources?keyword=${encodeURIComponent(keyword)}${status ? `&status=${status}` : ''}`),
  documentTree: libraryId => request(`/api/document-libraries/${libraryId}/tree`),
  documentTemplateBindings: libraryId => request(`/api/document-libraries/${libraryId}/template-bindings`),
  bindDocumentTemplate: (libraryId, knowledge_flow_template_id) => request(`/api/document-libraries/${libraryId}/template-bindings`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ knowledge_flow_template_id }) }),
  bindDocumentTemplates: (libraryId, knowledge_flow_template_ids) => request(`/api/document-libraries/${libraryId}/template-bindings/batch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ knowledge_flow_template_ids }) }),
  unbindDocumentTemplate: (libraryId, templateId) => request(`/api/document-libraries/${libraryId}/template-bindings/${templateId}`, { method: 'DELETE' }),
  processDocumentLibrary: libraryId => request(`/api/document-libraries/${libraryId}/process`, { method: 'POST' }),
  processSelectedDocumentSources: (libraryId, source_ids) => request(`/api/document-libraries/${libraryId}/process-selected`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_ids }) }),
  librarySources: (libraryId, params = {}) => request(`/api/document-libraries/${libraryId}/sources?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined)).toString()}`),
  sourceImportPreflight: (libraryId, entries) => request(`/api/document-libraries/${libraryId}/sources/import-preflight`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ entries }) }),
  importSources: (libraryId, form) => request(`/api/document-libraries/${libraryId}/sources/batch`, { method: 'POST', body: form }),
  uploadSources: (libraryId, form) => request(`/api/document-libraries/${libraryId}/sources/upload`, { method: 'POST', body: form }),
  sourceVersions: sourceId => request(`/api/sources/${sourceId}/versions`),
  replaceSource: (sourceId, form) => request(`/api/sources/${sourceId}/replace`, { method: 'POST', body: form }),
  reactivateSourceVersion: (sourceId, versionId, expected_current_version_id) => request(
    `/api/sources/${sourceId}/versions/${versionId}/reactivate`,
    json('POST', { expected_current_version_id }),
  ),
  deleteSource: sourceId => request(`/api/sources/${sourceId}`, { method: 'DELETE' }),
  retrySource: sourceId => request(`/api/sources/${sourceId}/retry`, { method: 'POST' }),
  sourceDetail: (sourceId, versionId = '', flowRunId = '') => request(`/api/sources/${sourceId}/detail?${new URLSearchParams(Object.entries({ version_id: versionId, flow_run_id: flowRunId }).filter(([, value]) => value)).toString()}`),
  retryParseJob: versionId => request(`/api/source-versions/${versionId}/parse/retry`, { method: 'POST' }),
  parsedDocument: id => request(`/api/parsed-documents/${id}`),
  parsedDocumentContent: (id, params = {}) => request(`/api/parsed-documents/${id}/content?${new URLSearchParams(params)}`),
  parsedDocumentAnchors: id => request(`/api/parsed-documents/${id}/anchors`),
  reviewParsedDocument: (id, body) => request(`/api/parsed-documents/${id}/review`, json('POST', body)),
  batchReviewParsedDocuments: (libraryId, items) => request(
    `/api/document-libraries/${libraryId}/parsed-documents/review-batch`, json('POST', { items }),
  ),
  flowChunkSetReview: id => request(`/api/flow-chunk-sets/${id}/review`),
  freezeFlowChunkSet: id => request(`/api/flow-chunk-sets/${id}/freeze`, { method: 'POST' }),
  updateFlowChunk: (chunkId, body) => request(`/api/flow-chunks/${chunkId}`, json('PATCH', body)),
  splitFlowChunk: (chunkId, body) => request(`/api/flow-chunks/${chunkId}/split`, json('POST', body)),
  mergeFlowChunks: body => request('/api/flow-chunks/merge', json('POST', body)),
  deleteFlowChunk: (chunkId, revisionNo) => request(`/api/flow-chunks/${chunkId}?expected_revision_no=${encodeURIComponent(revisionNo)}`, { method: 'DELETE' }),
  reviewFlowChunk: (chunkId, body) => request(`/api/flow-chunks/${chunkId}/review`, json('POST', body)),
  batchReviewFlowChunks: body => request('/api/flow-chunks/review-batch', json('POST', body)),
  reopenFlowChunk: chunkId => request(`/api/flow-chunks/${chunkId}/reopen`, { method: 'POST' }),
  sourceDownloadUrl: (sourceId, versionId) => `/api/sources/${sourceId}/versions/${versionId}/download`,
  sourcePreviewUrl: (sourceId, versionId) => `/api/sources/${sourceId}/versions/${versionId}/preview`,
  documentDeletionPreflight: body => request('/api/document-deletions/preflight', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  requestDocumentDeletion: body => request('/api/document-deletions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  retryDocumentDeletion: jobId => request(`/api/document-deletion-jobs/${jobId}/retry`, { method: 'POST' }),
  knowledgeLibraries: type => request(`/api/knowledge-libraries${type ? `?knowledge_type=${type}` : ''}`),
  knowledgeLibraryDeleteCheck: libraryId => request(`/api/knowledge-libraries/${libraryId}/delete-check`),
  deleteKnowledgeLibrary: libraryId => request(`/api/knowledge-libraries/${libraryId}`, { method: 'DELETE' }),
  knowledgeLibraryDeletionPreflight: body => request('/api/knowledge-libraries/deletions/preflight', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  requestKnowledgeLibraryDeletions: body => request('/api/knowledge-libraries/deletions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  deletionJobs: libraryId => request(`/api/knowledge-libraries/${libraryId}/deletion-jobs`),
  retryDeletion: jobId => request(`/api/knowledge-library-deletion-jobs/${jobId}/retry`, { method: 'POST' }),
  knowledgeItems: libraryId => request(`/api/knowledge-libraries/${libraryId}/items`),
  qaPairs: (libraryId, params = {}) => request(`/api/knowledge-libraries/${libraryId}/qa-pairs?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined)).toString()}`),
  updateKnowledgeItem: (itemId, body) => request(`/api/knowledge/items/${itemId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  reviewKnowledgeItem: (itemId, body) => request(`/api/knowledge/items/${itemId}/review`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  batchReviewKnowledgeItems: (libraryId, body) => request(`/api/knowledge-libraries/${libraryId}/review/batch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  knowledgeReviewSummary: libraryId => request(`/api/knowledge-libraries/${libraryId}/review-summary`),
  publishKnowledgeVectors: (libraryId, body) => request(`/api/knowledge-libraries/${libraryId}/vector-publish`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  graph: libraryId => request(`/api/knowledge-libraries/${libraryId}/graph`),
  graphOverview: libraryId => request(`/api/knowledge-libraries/${libraryId}/graph/overview`),
  graphTypeFacets: libraryId => request(`/api/knowledge-libraries/${libraryId}/graph/type-facets`),
  changes: libraryId => request(`/api/knowledge-libraries/${libraryId}/changes`),
  vectorStatus: libraryId => request(`/api/knowledge-libraries/${libraryId}/vector-status`),
  knowledgeItemSources: itemId => request(`/api/knowledge-items/${itemId}/sources`),
  graphEntities: (libraryId, q = '') => request(`/api/knowledge-libraries/${libraryId}/graph/entities?q=${encodeURIComponent(q)}`),
  graphEntity: (libraryId, entityId) => request(`/api/knowledge-libraries/${libraryId}/graph/entities/${entityId}`),
  graphNeighborPreview: (libraryId, entityId, depth = 1, filters = {}) => request(`/api/knowledge-libraries/${libraryId}/graph/entities/${entityId}/neighbors/preview?${graphNeighborQuery(depth, filters)}`),
  graphNeighbors: (libraryId, entityId, depth = 1, filters = {}, confirmLarge = false) => request(`/api/knowledge-libraries/${libraryId}/graph/entities/${entityId}/neighbors?${graphNeighborQuery(depth, filters, confirmLarge)}`),
  graphEvidence: (libraryId, relationId) => request(`/api/knowledge-libraries/${libraryId}/graph/relations/${relationId}/evidence`),
  knowledgeJobs: () => request('/api/knowledge-jobs'),
  createKnowledgeJob: body => request('/api/knowledge-jobs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  manageKnowledgeJobs: body => request('/api/knowledge-jobs/batch-actions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  knowledgeJobLogs: jobId => request(`/api/knowledge-jobs/${jobId}/logs`),
  knowledgeJobChunkGenerations: (jobId, failedOnly = false) => request(`/api/knowledge-jobs/${jobId}/chunk-generations${failedOnly ? '?failed_only=true' : ''}`),
  knowledgeJobInputPreparations: jobId => request(`/api/knowledge-jobs/${jobId}/input-preparations`),
  regenerateKnowledgeJob: jobId => request(`/api/knowledge-jobs/${jobId}/regenerate`, { method: 'POST' }),
  reprepareKnowledgeJobInput: jobId => request(`/api/knowledge-jobs/${jobId}/reprepare-input`, { method: 'POST' }),
  retryFailedGenerationUnits: jobId => request(`/api/knowledge-jobs/${jobId}/retry-failed`, { method: 'POST' }),
  knowledgeTypes: () => request('/api/developer/knowledge-types'),
  createKnowledgeType: body => request('/api/developer/knowledge-types', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  reviseKnowledgeType: (id, body) => request(`/api/developer/knowledge-types/${id}/revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  reviseKnowledgeTypeStorageBindings: (id, body) => request(`/api/developer/knowledge-types/${id}/storage-bindings`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateKnowledgeType: id => request(`/api/developer/knowledge-types/${id}/validate`, { method: 'POST' }),
  publishKnowledgeType: id => request(`/api/developer/knowledge-types/${id}/publish`, { method: 'POST' }),
  standardPipelines: () => request('/api/developer/standard-pipelines'),
  developerSamples: (purpose = '') => request(`/api/developer/samples${purpose ? `?purpose=${encodeURIComponent(purpose)}` : ''}`),
  developerSample: code => request(`/api/developer/samples/${encodeURIComponent(code)}`),
  operatorCatalog: (params = {}) => request(`/api/developer/operator-catalog?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined)).toString()}`),
  operatorCatalogFacets: () => request('/api/developer/operator-catalog/facets'),
  operatorCandidates: (payload) => request('/api/developer/operator-catalog/candidates', json('POST', payload)),
  resolveStandardFlow: (payload) => request('/api/developer/flow-compiler/resolve', json('POST', payload)),
  operatorPlugins: () => request('/api/developer/operator-plugins'),
  registerOperatorPlugin: manifest => request('/api/developer/operator-plugins', json('POST', { manifest })),
  validateOperatorPlugin: (code, version) => request(`/api/developer/operator-plugins/${encodeURIComponent(code)}/versions/${version}/validate`, { method: 'POST' }),
  operatorValidation: id => request(`/api/developer/operator-validations/${id}`),
  publishOperatorPlugin: (code, version) => request(`/api/developer/operator-plugins/${encodeURIComponent(code)}/versions/${version}/publish`, { method: 'POST' }),
  operatorDetail: code => request(`/api/developer/operator-catalog/${encodeURIComponent(code)}`),
  promptTemplates: (params = {}) => request(`/api/developer/prompt-templates?${new URLSearchParams(Object.entries(params).filter(([, value]) => value)).toString()}`),
  qualityProfiles: (params = {}) => request(`/api/developer/quality-profiles?${new URLSearchParams(Object.entries(params).filter(([, value]) => value)).toString()}`),
  flowSubgraphs: () => request('/api/developer/flow-subgraphs'),
  createFlowSubgraph: body => request('/api/developer/flow-subgraphs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  flowSubgraphRevisions: id => request(`/api/developer/flow-subgraphs/${id}/revisions`),
  flowSubgraphReferences: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/references`),
  flowSubgraphRevision: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}`),
  copyFlowSubgraphDraft: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/copy`, { method: 'POST' }),
  updateFlowSubgraphDraft: (id, revision, body) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateFlowSubgraphDraft: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/validate`, { method: 'POST' }),
  publishFlowSubgraphDraft: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/publish`, { method: 'POST' }),
  flowTemplates: () => request('/api/developer/knowledge-flow-templates'),
  managedFlowTemplates: () => request('/api/developer/managed-flow-templates'),
  graphEntityTypes: () => request('/api/developer/graph-entity-types'),
  previewGraphPrompt: body => request('/api/developer/graph-prompts/preview', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  resolveGraphEntityTypes: body => request('/api/developer/graph-entity-types/resolve', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  materializeManagedFlow: code => request(`/api/developer/managed-flow-templates/${code}/materialize`, { method: 'POST' }),
  previewFlowCompilation: body => request('/api/developer/flow-compiler/preview', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  detachFlowToAdvanced: id => request(`/api/developer/knowledge-flow-templates/${id}/detach-to-advanced`, { method: 'POST' }),
  previewFlowToAdvanced: id => request(`/api/developer/knowledge-flow-templates/${id}/detach-to-advanced?preview=true`, { method: 'POST' }),
  createFlowTemplate: body => request('/api/developer/knowledge-flow-templates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  updateFlowTemplate: (id, body) => request(`/api/developer/knowledge-flow-templates/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  archiveFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}`, { method: 'DELETE' }),
  defaultFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}/set-default`, { method: 'POST' }),
  validateFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}/validate`, { method: 'POST' }),
  publishFlowTemplate: (id, body) => request(`/api/developer/knowledge-flow-templates/${id}/publish`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  sampleFlowTemplate: (id, sample_id) => request(`/api/developer/knowledge-flow-templates/${id}/sample-run`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sample_id }) }),
  executionSnapshot: id => request(`/api/developer/execution-snapshots/${id}`),
  flowRuns: () => request('/api/developer/flow-runs'),
  flowRun: id => request(`/api/developer/flow-runs/${id}`),
  flowRunCapabilities: () => request('/api/developer/flow-runs/capabilities'),
  debugRunOptions: (templateId, revisionKind = 'draft') => request(`/api/developer/debug-runs/options?template_id=${encodeURIComponent(templateId)}&revision_kind=${encodeURIComponent(revisionKind)}`),
  debugRunPreflight: body => request('/api/developer/debug-runs/preflight', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  createDebugRun: body => request('/api/developer/debug-runs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  debugRunMaterialization: id => request(`/api/developer/debug-runs/${id}/flow-materialization`),
  applyDebugRunToDraft: (id, body) => request(`/api/developer/debug-runs/${id}/apply-to-draft`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  saveDebugRunAsFlow: (id, body) => request(`/api/developer/debug-runs/${id}/save-as-flow`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  flowRunEvents: (id, cursor = 0, limit = 100) => request(`/api/developer/flow-runs/${id}/events?after=${cursor}&limit=${limit}`),
  createDerivedRun: (id, body) => request(`/api/developer/flow-runs/${id}/derived-runs`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  cancelFlowRun: id => request(`/api/developer/flow-runs/${id}/cancel`, { method: 'POST' }),
  persistDerivedParameters: (id, body) => request(`/api/developer/flow-runs/${id}/persist-parameters`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  commitFlowRun: (id, body) => request(`/api/developer/flow-runs/${id}/commit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  artifactDetail: id => request(`/api/developer/artifacts/${id}`),
  sinkPreviewCandidates: (runId, previewId, offset = 0, limit = 50) => request(`/api/developer/flow-runs/${encodeURIComponent(runId)}/sink-previews/${encodeURIComponent(previewId)}/candidates?offset=${offset}&limit=${limit}`),
  artifactContent: (id, offset = 0, limit = 50) => request(`/api/developer/artifacts/${id}/content?offset=${offset}&limit=${limit}`),
  vectorIndexes: () => request('/api/developer/vector-indexes'),
  vectorStorageOverview: () => request('/api/vector-storage/overview'),
  vectorStorageCollections: (params = {}) => request(`/api/vector-storage/collections?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined).map(([key, value]) => [key, String(value)])).toString()}`),
  vectorStorageCollection: name => request(`/api/vector-storage/collections/${encodeURIComponent(name)}`),
  vectorStoragePartition: (collection, partition) => request(`/api/vector-storage/collections/${encodeURIComponent(collection)}/partitions/${encodeURIComponent(partition)}`),
  verifyVectorPartition: (collection, partition) => request(`/api/vector-storage/collections/${encodeURIComponent(collection)}/partitions/${encodeURIComponent(partition)}/verify`, { method: 'POST' }),
  loadVectorPartition: (collection, partition) => request(`/api/vector-storage/collections/${encodeURIComponent(collection)}/partitions/${encodeURIComponent(partition)}/load`, { method: 'POST' }),
  releaseVectorPartition: (collection, partition) => request(`/api/vector-storage/collections/${encodeURIComponent(collection)}/partitions/${encodeURIComponent(partition)}/release`, { method: 'POST' }),
  managedCollections: () => request('/api/developer/managed-collections'),
  reconcileManagedCollection: id => request(`/api/developer/managed-collections/${id}/reconcile`, { method: 'POST' }),
  managedCollectionDeleteCheck: id => request(`/api/developer/managed-collections/${id}/delete-check`),
  deleteManagedCollection: id => request(`/api/developer/managed-collections/${id}`, { method: 'DELETE' }),
  managedCollectionDeletionJobs: id => request(`/api/developer/managed-collections/${id}/deletion-jobs`),
  retryManagedCollectionDeletion: id => request(`/api/developer/managed-collection-deletion-jobs/${id}/retry`, { method: 'POST' }),
  createIndexProfile: body => request('/api/developer/index-profiles', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  reviseIndexProfile: (id, body) => request(`/api/developer/index-profiles/${id}/revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateIndexProfile: id => request(`/api/developer/index-profiles/${id}/validate`, { method: 'POST' }),
  publishIndexProfile: id => request(`/api/developer/index-profiles/${id}/publish`, { method: 'POST' }),
  archiveIndexProfile: id => request(`/api/developer/index-profiles/${id}/archive`, { method: 'POST' }),
  vectorSyncJobs: libraryId => request(`/api/vector-sync-jobs${libraryId ? `?knowledge_library_id=${libraryId}` : ''}`),
  runVectorSync: jobId => request(`/api/vector-sync-jobs/${jobId}/run`, { method: 'POST' }),
  instance: () => request('/api/instance'),
  projects: () => request('/api/projects'),
  createProject: body => request('/api/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  createProjectTask: (projectId, body) => request(`/api/projects/${projectId}/tasks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  milvusTargets: () => request('/api/milvus-targets'),
  createMilvusTarget: body => request('/api/milvus-targets', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  patchMilvusTarget: (id, body) => request(`/api/milvus-targets/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  verifyMilvusTarget: id => request(`/api/milvus-targets/${id}/verify`, { method: 'POST' }),
  checkMilvusTargetHealth: id => request(`/api/milvus-targets/${id}/health-check`, { method: 'POST' }),
  checkMilvusTargetCollections: id => request(`/api/milvus-targets/${id}/collections-check`, { method: 'POST' }),
  putAuthoringMilvusTarget: milvus_target_id => request('/api/instance/milvus-authoring-target', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ milvus_target_id }) }),
  sharedDeployments: () => request('/api/institution-deployments'),
  createSharedDeployment: body => request('/api/institution-deployments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  patchSharedDeployment: (deploymentId, body) => request(`/api/institution-deployments/${deploymentId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  deploymentProjects: deploymentId => request(`/api/institution-deployments/${deploymentId}/projects`),
  replaceDeploymentProjects: (deploymentId, project_ids) => request(`/api/institution-deployments/${deploymentId}/projects`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project_ids }) }),
  instanceReleaseTarget: stage => request(`/api/instance/release-targets/${stage}`),
  putInstanceReleaseTarget: (stage, body) => request(`/api/instance/release-targets/${stage}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  deploymentTasks: projectId => request(`/api/projects/${projectId}/release-tasks`),
  createDeploymentTask: (projectId, body) => request(`/api/projects/${projectId}/release-tasks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  authorizations: projectId => request(`/api/projects/${projectId}/authorizations`),
  putDeploymentRoute: (projectId, taskId, body) => request(`/api/projects/${projectId}/release-tasks/${taskId}/org-routes`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateRouting: (projectId, stage) => request(`/api/projects/${projectId}/routing/validate?release_stage=${encodeURIComponent(stage)}`, { method: 'POST' }),
  routingDiff: (projectId, stage) => request(`/api/projects/${projectId}/routing/diff?release_stage=${encodeURIComponent(stage)}`),
  publishRouting: (projectId, body) => request(`/api/projects/${projectId}/publications`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  routeVersions: (projectId, stage) => request(`/api/projects/${projectId}/route-versions?release_stage=${encodeURIComponent(stage)}`),
  routeVersion: (projectId, version, stage) => request(`/api/projects/${projectId}/route-versions/${version}?release_stage=${encodeURIComponent(stage)}`),
  rollbackRouting: (projectId, version, body) => request(`/api/projects/${projectId}/publications/rollback/${version}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  freezeRouting: (projectId, stage) => request(`/api/projects/${projectId}/route-versions?release_stage=${encodeURIComponent(stage)}`, { method: 'POST' }),
  createInstitutionReleaseDraft: body => request('/api/institution-deployments/drafts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  institutionReleaseDraft: draftId => request(`/api/institution-deployments/drafts/${draftId}`),
  updateInstitutionReleaseDraft: (draftId, body) => request(`/api/institution-deployments/drafts/${draftId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  institutionReleasePlan: draftId => request(`/api/institution-deployments/drafts/${draftId}/plan`),
  institutionReleaseAssetOptions: draftId => request(`/api/institution-deployments/drafts/${draftId}/asset-options`),
  freezeInstitutionRelease: draftId => request(`/api/institution-deployments/drafts/${draftId}/freeze`, { method: 'POST' }),
  institutionReleases: deploymentId => request(`/api/institution-deployments/releases${deploymentId ? `?target_deployment_id=${encodeURIComponent(deploymentId)}` : ''}`),
  institutionRelease: releaseId => request(`/api/institution-deployments/releases/${releaseId}`),
  buildInstitutionRelease: releaseId => request(`/api/institution-deployments/releases/${releaseId}/build`, { method: 'POST' }),
  health: () => request('/api/health'),
  observabilityComponents: () => request('/api/observability/components'),
  createComponentCheck: components => request('/api/observability/check-runs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ components }) }),
  componentCheckRun: runId => request(`/api/observability/check-runs/${runId}`),
  localMilvusConfigurations: () => request('/api/local/milvus-configurations'),
  putLocalMilvusConfiguration: (slot, body) => request(`/api/local/milvus-configurations/${slot}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  verifyLocalMilvusConfiguration: slot => request(`/api/local/milvus-configurations/${slot}/verify`, { method: 'POST' }),
  promoteLocalMilvusCandidate: () => request('/api/local/milvus-configurations/candidate_target/promote', { method: 'POST' }),
  importedRouteCandidates: jobId => request(`/api/imported-route-candidates${jobId ? `?migration_job_id=${encodeURIComponent(jobId)}` : ''}`),
  activateImportedRouteCandidate: candidateId => request(`/api/imported-route-candidates/${candidateId}/activate`, { method: 'POST' }),
  activateReadyRouteCandidates: candidate_ids => request('/api/imported-route-candidates/activate-ready', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ candidate_ids }) }),
  migrationActivationPreflight: jobId => request(`/api/migrations/${jobId}/activation-preflight`, { method: 'POST' }),
  activateMigrationReadyRoutes: jobId => request(`/api/migrations/${jobId}/activate-ready`, { method: 'POST' }),
  migrations: direction => request(`/api/migrations${direction ? `?direction=${direction}` : ''}`),
  migrationJob: jobId => request(`/api/migrations/${jobId}`),
  migrationPackageUrl: jobId => `/api/migrations/${jobId}/package`,
  inspectMigration: form => request('/api/migrations/import/inspect', { method: 'POST', body: form }),
  importMigration: body => request('/api/migrations/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  retryMigration: jobId => request(`/api/migrations/${jobId}/retry`, { method: 'POST' }),
  resumeMigration: (jobId, body = {}) => request(`/api/migrations/${jobId}/resume`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  knowledgeAssetGcPlan: () => request('/api/knowledge-asset-gc/plan'),
  createKnowledgeAssetGcJob: body => request('/api/knowledge-asset-gc/jobs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
}
