async function request(path, options = {}) {
  const response = await fetch(path, { credentials: 'same-origin', ...options })
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || '请求失败')
  return response.status === 204 ? null : response.json()
}

function graphNeighborQuery(depth, filters = {}, confirmLarge = false) {
  const params = new URLSearchParams({ depth: String(depth) })
  for (const value of filters.entityTypes || []) params.append('entity_types', value)
  for (const value of filters.relationTypes || []) params.append('relation_types', value)
  if (confirmLarge) params.set('confirm_large', 'true')
  return params.toString()
}

export const api = {
  servingCategories: () => request('/api/serving-categories'),
  modelServings: () => request('/api/model-servings'),
  createModelServing: body => request('/api/model-servings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  patchModelServing: (id, body) => request(`/api/model-servings/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  testModelServing: id => request(`/api/model-servings/${id}/test`, { method: 'POST' }),
  defaultModelServing: id => request(`/api/model-servings/${id}/set-default`, { method: 'POST' }),
  modelServingReferences: id => request(`/api/model-servings/${id}/references`),
  deleteModelServing: id => request(`/api/model-servings/${id}`, { method: 'DELETE' }),
  embeddingServings: () => request('/api/embedding-servings'),
  createEmbeddingServing: body => request('/api/embedding-servings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  patchEmbeddingServing: (id, body) => request(`/api/embedding-servings/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  testEmbeddingServing: id => request(`/api/embedding-servings/${id}/test`, { method: 'POST' }),
  defaultEmbeddingServing: id => request(`/api/embedding-servings/${id}/set-default`, { method: 'POST' }),
  embeddingServingReferences: id => request(`/api/embedding-servings/${id}/references`),
  deleteEmbeddingServing: id => request(`/api/embedding-servings/${id}`, { method: 'DELETE' }),
  dashboardOverview: () => request('/api/dashboard/overview'),
  documentLibraries: (keyword = '', status = '') => request(`/api/document-libraries?keyword=${encodeURIComponent(keyword)}${status ? `&status=${encodeURIComponent(status)}` : ''}`),
  createDocumentLibrary: body => request('/api/document-libraries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  sources: (libraryId = '', keyword = '', status = '') => request(libraryId ? `/api/document-libraries/${libraryId}/sources?keyword=${encodeURIComponent(keyword)}${status ? `&status=${status}` : ''}` : `/api/sources?keyword=${encodeURIComponent(keyword)}${status ? `&status=${status}` : ''}`),
  documentTree: libraryId => request(`/api/document-libraries/${libraryId}/tree`),
  documentTemplateBindings: libraryId => request(`/api/document-libraries/${libraryId}/template-bindings`),
  bindDocumentTemplate: (libraryId, knowledge_flow_template_id) => request(`/api/document-libraries/${libraryId}/template-bindings`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ knowledge_flow_template_id }) }),
  bindDocumentTemplates: (libraryId, knowledge_flow_template_ids) => request(`/api/document-libraries/${libraryId}/template-bindings/batch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ knowledge_flow_template_ids }) }),
  unbindDocumentTemplate: (libraryId, templateId) => request(`/api/document-libraries/${libraryId}/template-bindings/${templateId}`, { method: 'DELETE' }),
  processDocumentLibrary: libraryId => request(`/api/document-libraries/${libraryId}/process`, { method: 'POST' }),
  processSelectedDocumentSources: (libraryId, source_ids) => request(`/api/document-libraries/${libraryId}/process-selected`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_ids }) }),
  librarySources: (libraryId, params = {}) => request(`/api/document-libraries/${libraryId}/sources?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined)).toString()}`),
  sourceImportPreflight: (libraryId, entries) => request(`/api/document-libraries/${libraryId}/sources/import-preflight`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ entries }) }),
  importSources: (libraryId, form) => request(`/api/document-libraries/${libraryId}/sources/batch`, { method: 'POST', body: form }),
  uploadSources: (libraryId, form) => request(`/api/document-libraries/${libraryId}/sources/upload`, { method: 'POST', body: form }),
  sourceVersions: sourceId => request(`/api/sources/${sourceId}/versions`),
  replaceSource: (sourceId, form) => request(`/api/sources/${sourceId}/replace`, { method: 'POST', body: form }),
  deleteSource: sourceId => request(`/api/sources/${sourceId}`, { method: 'DELETE' }),
  retrySource: sourceId => request(`/api/sources/${sourceId}/retry`, { method: 'POST' }),
  sourceDetail: (sourceId, versionId = '', flowRunId = '') => request(`/api/sources/${sourceId}/detail?${new URLSearchParams(Object.entries({ version_id: versionId, flow_run_id: flowRunId }).filter(([, value]) => value)).toString()}`),
  sourceReview: (versionId, chunkSetId = '') => request(`/api/source-versions/${versionId}/review${chunkSetId ? `?chunk_set_id=${encodeURIComponent(chunkSetId)}` : ''}`),
  approveSourceReview: versionId => request(`/api/source-versions/${versionId}/review/approve`, { method: 'POST' }),
  retrySourcePreparation: versionId => request(`/api/source-versions/${versionId}/preparation/retry`, { method: 'POST' }),
  rechunkSourceVersion: (versionId, execution_snapshot_id = null) => request(`/api/source-versions/${versionId}/preparation/rechunk`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ execution_snapshot_id }) }),
  batchReviewSourceChunks: (versionId, body) => request(`/api/source-versions/${versionId}/review/batch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  updateSourceChunk: (chunkId, body) => request(`/api/source-chunks/${chunkId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  splitSourceChunk: (chunkId, body) => request(`/api/source-chunks/${chunkId}/split`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  mergeSourceChunks: body => request('/api/source-chunks/merge', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  deleteSourceChunk: (chunkId, revisionNo) => request(`/api/source-chunks/${chunkId}?expected_revision_no=${encodeURIComponent(revisionNo)}`, { method: 'DELETE' }),
  reviewSourceChunk: (chunkId, body) => request(`/api/source-chunks/${chunkId}/review`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  reopenSourceChunk: chunkId => request(`/api/source-chunks/${chunkId}/reopen`, { method: 'POST' }),
  sourceDownloadUrl: (sourceId, versionId) => `/api/sources/${sourceId}/versions/${versionId}/download`,
  sourcePreviewUrl: (sourceId, versionId) => `/api/sources/${sourceId}/versions/${versionId}/preview`,
  documentDeletionPreflight: body => request('/api/document-deletions/preflight', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  requestDocumentDeletion: body => request('/api/document-deletions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  retryDocumentDeletion: jobId => request(`/api/document-deletion-jobs/${jobId}/retry`, { method: 'POST' }),
  knowledgeLibraries: type => request(`/api/knowledge-libraries${type ? `?knowledge_type=${type}` : ''}`),
  knowledgeLibraryDeleteCheck: libraryId => request(`/api/knowledge-libraries/${libraryId}/delete-check`),
  deleteKnowledgeLibrary: libraryId => request(`/api/knowledge-libraries/${libraryId}`, { method: 'DELETE' }),
  deletionJobs: libraryId => request(`/api/knowledge-libraries/${libraryId}/deletion-jobs`),
  retryDeletion: jobId => request(`/api/knowledge-library-deletion-jobs/${jobId}/retry`, { method: 'POST' }),
  knowledgeItems: libraryId => request(`/api/knowledge-libraries/${libraryId}/items`),
  qaPairs: (libraryId, params = {}) => request(`/api/knowledge-libraries/${libraryId}/qa-pairs?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined)).toString()}`),
  graph: libraryId => request(`/api/knowledge-libraries/${libraryId}/graph`),
  graphOverview: libraryId => request(`/api/knowledge-libraries/${libraryId}/graph/overview`),
  changes: libraryId => request(`/api/knowledge-libraries/${libraryId}/changes`),
  vectorStatus: libraryId => request(`/api/knowledge-libraries/${libraryId}/vector-status`),
  knowledgeItemSources: itemId => request(`/api/knowledge-items/${itemId}/sources`),
  graphEntities: (libraryId, q = '') => request(`/api/knowledge-libraries/${libraryId}/graph/entities?q=${encodeURIComponent(q)}`),
  graphEntity: (libraryId, entityId) => request(`/api/knowledge-libraries/${libraryId}/graph/entities/${entityId}`),
  graphNeighborPreview: (libraryId, entityId, depth = 1, filters = {}) => request(`/api/knowledge-libraries/${libraryId}/graph/entities/${entityId}/neighbors/preview?${graphNeighborQuery(depth, filters)}`),
  graphNeighbors: (libraryId, entityId, depth = 1, filters = {}, confirmLarge = false) => request(`/api/knowledge-libraries/${libraryId}/graph/entities/${entityId}/neighbors?${graphNeighborQuery(depth, filters, confirmLarge)}`),
  graphEvidence: (libraryId, relationId) => request(`/api/knowledge-libraries/${libraryId}/graph/relations/${relationId}/evidence`),
  knowledgeJobs: () => request('/api/knowledge-jobs'),
  createKnowledgeJob: body => request('/api/knowledge-jobs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  manageKnowledgeJobs: body => request('/api/knowledge-jobs/batch-actions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  knowledgeJobLogs: jobId => request(`/api/knowledge-jobs/${jobId}/logs`),
  knowledgeJobChunkGenerations: (jobId, failedOnly = false) => request(`/api/knowledge-jobs/${jobId}/chunk-generations${failedOnly ? '?failed_only=true' : ''}`),
  knowledgeTypes: () => request('/api/developer/knowledge-types'),
  createKnowledgeType: body => request('/api/developer/knowledge-types', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  reviseKnowledgeType: (id, body) => request(`/api/developer/knowledge-types/${id}/revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateKnowledgeType: id => request(`/api/developer/knowledge-types/${id}/validate`, { method: 'POST' }),
  publishKnowledgeType: id => request(`/api/developer/knowledge-types/${id}/publish`, { method: 'POST' }),
  standardPipelines: () => request('/api/developer/standard-pipelines'),
  sourcePreparationChunker: () => request('/api/developer/source-preparation/chunker'),
  createSourcePreparationChunkerRevision: body => request('/api/developer/source-preparation/chunker/revisions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  operatorCatalog: (params = {}) => request(`/api/developer/operator-catalog?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined)).toString()}`),
  operatorCatalogFacets: () => request('/api/developer/operator-catalog/facets'),
  operatorDetail: code => request(`/api/developer/operator-catalog/${encodeURIComponent(code)}`),
  promptTemplates: () => request('/api/developer/prompt-templates'),
  qualityProfiles: () => request('/api/developer/quality-profiles'),
  flowSubgraphs: () => request('/api/developer/flow-subgraphs'),
  flowSubgraphRevision: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}`),
  copyFlowSubgraphDraft: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/copy`, { method: 'POST' }),
  updateFlowSubgraphDraft: (id, revision, body) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateFlowSubgraphDraft: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/validate`, { method: 'POST' }),
  publishFlowSubgraphDraft: (id, revision) => request(`/api/developer/flow-subgraphs/${id}/revisions/${revision}/publish`, { method: 'POST' }),
  flowTemplates: () => request('/api/developer/knowledge-flow-templates'),
  createFlowTemplate: body => request('/api/developer/knowledge-flow-templates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  updateFlowTemplate: (id, body) => request(`/api/developer/knowledge-flow-templates/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  archiveFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}`, { method: 'DELETE' }),
  defaultFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}/set-default`, { method: 'POST' }),
  validateFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}/validate`, { method: 'POST' }),
  publishFlowTemplate: id => request(`/api/developer/knowledge-flow-templates/${id}/publish`, { method: 'POST' }),
  sampleFlowTemplate: (id, sample_id) => request(`/api/developer/knowledge-flow-templates/${id}/sample-run`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sample_id }) }),
  executionSnapshot: id => request(`/api/developer/execution-snapshots/${id}`),
  flowRuns: () => request('/api/developer/flow-runs'),
  flowRun: id => request(`/api/developer/flow-runs/${id}`),
  flowRunCapabilities: () => request('/api/developer/flow-runs/capabilities'),
  flowRunEvents: (id, cursor = 0, limit = 100) => request(`/api/developer/flow-runs/${id}/events?after=${cursor}&limit=${limit}`),
  createDerivedRun: (id, body) => request(`/api/developer/flow-runs/${id}/derived-runs`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  cancelFlowRun: id => request(`/api/developer/flow-runs/${id}/cancel`, { method: 'POST' }),
  persistDerivedParameters: (id, body) => request(`/api/developer/flow-runs/${id}/persist-parameters`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  commitFlowRun: (id, body) => request(`/api/developer/flow-runs/${id}/commit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  artifactDetail: id => request(`/api/developer/artifacts/${id}`),
  artifactContent: (id, offset = 0, limit = 50) => request(`/api/developer/artifacts/${id}/content?offset=${offset}&limit=${limit}`),
  vectorIndexes: () => request('/api/developer/vector-indexes'),
  vectorStorageOverview: () => request('/api/vector-storage/overview'),
  vectorStorageCollections: (params = {}) => request(`/api/vector-storage/collections?${new URLSearchParams(Object.entries(params).filter(([, value]) => value !== '' && value !== null && value !== undefined).map(([key, value]) => [key, String(value)])).toString()}`),
  vectorStorageCollection: name => request(`/api/vector-storage/collections/${encodeURIComponent(name)}`),
  vectorStoragePartition: (collection, partition) => request(`/api/vector-storage/collections/${encodeURIComponent(collection)}/partitions/${encodeURIComponent(partition)}`),
  verifyVectorPartition: (collection, partition) => request(`/api/vector-storage/collections/${encodeURIComponent(collection)}/partitions/${encodeURIComponent(partition)}/verify`, { method: 'POST' }),
  loadVectorPartition: (collection, partition) => request(`/api/vector-storage/collections/${encodeURIComponent(collection)}/partitions/${encodeURIComponent(partition)}/load`, { method: 'POST' }),
  releaseVectorPartition: (collection, partition) => request(`/api/vector-storage/collections/${encodeURIComponent(collection)}/partitions/${encodeURIComponent(partition)}/release`, { method: 'POST' }),
  managedCollections: () => request('/api/developer/managed-collections'),
  reconcileManagedCollection: id => request(`/api/developer/managed-collections/${id}/reconcile`, { method: 'POST' }),
  managedCollectionDeleteCheck: id => request(`/api/developer/managed-collections/${id}/delete-check`),
  deleteManagedCollection: id => request(`/api/developer/managed-collections/${id}`, { method: 'DELETE' }),
  managedCollectionDeletionJobs: id => request(`/api/developer/managed-collections/${id}/deletion-jobs`),
  retryManagedCollectionDeletion: id => request(`/api/developer/managed-collection-deletion-jobs/${id}/retry`, { method: 'POST' }),
  createIndexProfile: body => request('/api/developer/index-profiles', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  reviseIndexProfile: (id, body) => request(`/api/developer/index-profiles/${id}/revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateIndexProfile: id => request(`/api/developer/index-profiles/${id}/validate`, { method: 'POST' }),
  publishIndexProfile: id => request(`/api/developer/index-profiles/${id}/publish`, { method: 'POST' }),
  archiveIndexProfile: id => request(`/api/developer/index-profiles/${id}/archive`, { method: 'POST' }),
  vectorSyncJobs: libraryId => request(`/api/vector-sync-jobs${libraryId ? `?knowledge_library_id=${libraryId}` : ''}`),
  queueVectorSync: libraryId => request(`/api/knowledge-libraries/${libraryId}/vector-sync-jobs`, { method: 'POST' }),
  runVectorSync: jobId => request(`/api/vector-sync-jobs/${jobId}/run`, { method: 'POST' }),
  instance: () => request('/api/instance'),
  projects: () => request('/api/projects'),
  createProject: body => request('/api/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  createProjectTask: (projectId, body) => request(`/api/projects/${projectId}/tasks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  deployments: projectId => request(`/api/projects/${projectId}/deployments`),
  sharedDeployments: () => request('/api/deployments'),
  createSharedDeployment: body => request('/api/deployments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  patchSharedDeployment: (deploymentId, body) => request(`/api/deployments/${deploymentId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  putDeploymentTarget: (deploymentId, stage, body) => request(`/api/deployments/${deploymentId}/targets/${stage}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  patchDeploymentStage: (deploymentId, body) => request(`/api/deployments/${deploymentId}/release-stage`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  bindDeploymentProject: (deploymentId, projectId) => request(`/api/deployments/${deploymentId}/projects`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project_id: projectId }) }),
  createDeployment: (projectId, body) => request(`/api/projects/${projectId}/deployments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  patchDeployment: (projectId, deploymentId, body) => request(`/api/projects/${projectId}/deployments/${deploymentId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  deploymentTasks: deploymentId => request(`/api/project-deployments/${deploymentId}/tasks`),
  createDeploymentTask: (deploymentId, body) => request(`/api/project-deployments/${deploymentId}/tasks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  authorizations: deploymentId => request(`/api/project-deployments/${deploymentId}/authorizations`),
  putDeploymentRoute: (deploymentId, taskId, body) => request(`/api/project-deployments/${deploymentId}/tasks/${taskId}/org-routes`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  validateRouting: deploymentId => request(`/api/project-deployments/${deploymentId}/routing/validate`, { method: 'POST' }),
  routingDiff: (deploymentId, stage) => request(`/api/project-deployments/${deploymentId}/routing/diff?release_stage=${encodeURIComponent(stage)}`),
  publishRouting: (deploymentId, body) => request(`/api/project-deployments/${deploymentId}/routing/publish`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  routeVersions: (deploymentId, stage) => request(`/api/project-deployments/${deploymentId}/routing/versions?release_stage=${encodeURIComponent(stage)}`),
  routeVersion: (deploymentId, version, stage) => request(`/api/project-deployments/${deploymentId}/routing/versions/${version}?release_stage=${encodeURIComponent(stage)}`),
  rollbackRouting: (deploymentId, version, body) => request(`/api/project-deployments/${deploymentId}/routing/rollback/${version}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  freezeRouting: deploymentId => request(`/api/project-deployments/${deploymentId}/routing/freeze`, { method: 'POST' }),
  createInstitutionReleaseDraft: body => request('/api/institution-deployments/drafts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  institutionReleaseDraft: draftId => request(`/api/institution-deployments/drafts/${draftId}`),
  updateInstitutionReleaseDraft: (draftId, body) => request(`/api/institution-deployments/drafts/${draftId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  institutionReleasePlan: draftId => request(`/api/institution-deployments/drafts/${draftId}/plan`),
  institutionReleaseAssetOptions: draftId => request(`/api/institution-deployments/drafts/${draftId}/asset-options`),
  freezeInstitutionRelease: draftId => request(`/api/institution-deployments/drafts/${draftId}/freeze`, { method: 'POST' }),
  institutionReleases: deploymentId => request(`/api/institution-deployments/releases${deploymentId ? `?target_deployment_id=${encodeURIComponent(deploymentId)}` : ''}`),
  institutionRelease: releaseId => request(`/api/institution-deployments/releases/${releaseId}`),
  buildInstitutionRelease: releaseId => request(`/api/institution-deployments/releases/${releaseId}/build`, { method: 'POST' }),
  health: () => request('/api/health'),
  observabilityComponents: () => request('/api/observability/components'),
  createComponentCheck: components => request('/api/observability/check-runs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ components }) }),
  componentCheckRun: runId => request(`/api/observability/check-runs/${runId}`),
  localMilvusConfigurations: () => request('/api/local/milvus-configurations'),
  putLocalMilvusConfiguration: (slot, body) => request(`/api/local/milvus-configurations/${slot}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  verifyLocalMilvusConfiguration: slot => request(`/api/local/milvus-configurations/${slot}/verify`, { method: 'POST' }),
  promoteLocalMilvusCandidate: () => request('/api/local/milvus-configurations/candidate_target/promote', { method: 'POST' }),
  importedRouteCandidates: jobId => request(`/api/imported-route-candidates${jobId ? `?migration_job_id=${encodeURIComponent(jobId)}` : ''}`),
  activateImportedRouteCandidate: candidateId => request(`/api/imported-route-candidates/${candidateId}/activate`, { method: 'POST' }),
  activateReadyRouteCandidates: candidate_ids => request('/api/imported-route-candidates/activate-ready', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ candidate_ids }) }),
  migrationActivationPreflight: jobId => request(`/api/migrations/${jobId}/activation-preflight`, { method: 'POST' }),
  activateMigrationReadyRoutes: jobId => request(`/api/migrations/${jobId}/activate-ready`, { method: 'POST' }),
  migrationPlan: body => request('/api/migrations/export/plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  exportMigration: body => request('/api/migrations/export', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  migrations: direction => request(`/api/migrations${direction ? `?direction=${direction}` : ''}`),
  migrationJob: jobId => request(`/api/migrations/${jobId}`),
  migrationPackageUrl: jobId => `/api/migrations/${jobId}/package`,
  inspectMigration: form => request('/api/migrations/import/inspect', { method: 'POST', body: form }),
  importMigration: body => request('/api/migrations/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  retryMigration: jobId => request(`/api/migrations/${jobId}/retry`, { method: 'POST' }),
  resumeMigration: (jobId, body = {}) => request(`/api/migrations/${jobId}/resume`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
  knowledgeAssetGcPlan: () => request('/api/knowledge-asset-gc/plan'),
  createKnowledgeAssetGcJob: body => request('/api/knowledge-asset-gc/jobs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }),
}
