import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const router = readFileSync(new URL('../../router/index.js', import.meta.url), 'utf8')
const listing = readFileSync(new URL('./DocumentLibraryDetailView.vue', import.meta.url), 'utf8')
const workbench = readFileSync(new URL('./DocumentReviewWorkbenchView.vue', import.meta.url), 'utf8')
const preview = readFileSync(new URL('../../components/source-review/SourcePreviewPane.vue', import.meta.url), 'utf8')
const pdfPreview = readFileSync(new URL('../../components/source-review/PdfSourcePreview.vue', import.meta.url), 'utf8')
const docxPreview = readFileSync(new URL('../../components/source-review/DocxSourcePreview.vue', import.meta.url), 'utf8')
const structuredPreview = readFileSync(new URL('../../components/source-review/StructuredSourcePreview.vue', import.meta.url), 'utf8')
const previewScroll = readFileSync(new URL('../../components/source-review/sourcePreviewScroll.js', import.meta.url), 'utf8')
const chunkCard = readFileSync(new URL('../../components/source-review/ChunkCard.vue', import.meta.url), 'utf8')
const styles = readFileSync(new URL('../../styles-v7.css', import.meta.url), 'utf8')
const workspaceLayout = readFileSync(new URL('../../layouts/WorkspaceLayout.vue', import.meta.url), 'utf8')

test('document list routes every review entry to the immutable-version workbench', () => {
  assert.match(router, /documents\/:libraryId\/sources\/:sourceId\/versions\/:versionId\/review/)
  assert.match(router, /review[^\n]*meta:\s*\{\s*hideTopbar:\s*true\s*\}/)
  assert.match(workspaceLayout, /v-if="!hideTopbar" class="topbar"/)
  assert.match(listing, /openReviewWorkbench\(source\)/)
  assert.match(listing, /@click\.stop="openReviewWorkbench\(source\)"/)
  assert.match(listing, /sourceDownloadUrl/)
  assert.match(listing, />下载</)
  assert.doesNotMatch(listing, /review-workspace/)
})

test('workbench uses SourceAnchor preview, polling and independent focus/batch state', () => {
  assert.match(preview, /sourcePreviewUrl/)
  assert.doesNotMatch(preview, /<iframe/)
  assert.match(workbench, /setInterval\(load, 2000\)/)
  assert.match(workbench, /batchReviewSourceChunks/)
  assert.match(workbench, /selectedSourceAnchor/)
  assert.match(workbench, /:focused="focusedChunkId === chunk\.id"/)
  assert.match(workbench, /:checked="selectedIds\.includes\(chunk\.id\)"/)
  assert.match(chunkCard, /keydown\.enter\.space/)
})

test('PDF.js and DOCX evidence viewers expose multi-position highlights and explicit fallback states', () => {
  assert.match(pdfPreview, /import\('pdfjs-dist'\)/)
  assert.match(pdfPreview, /source-highlight/)
  assert.match(pdfPreview, /scrollTargetWithin/)
  assert.match(pdfPreview, /visiblePageNumber/)
  assert.match(pdfPreview, /version !== locateVersion/)
  assert.match(pdfPreview, /watch\(scale/)
  assert.match(pdfPreview, /await locateAnchor\(\)/)
  assert.match(docxPreview, /scrollTargetWithin/)
  assert.match(previewScroll, /container\.scrollTo/)
  assert.doesNotMatch(pdfPreview, /scrollIntoView/)
  assert.doesNotMatch(docxPreview, /scrollIntoView/)
  assert.match(docxPreview, /data-source-block/)
  assert.match(docxPreview, /highlighted/)
  assert.match(preview, /PdfSourcePreview/)
  assert.match(preview, /DocxSourcePreview/)
  assert.match(preview, /StructuredSourcePreview/)
  assert.match(structuredPreview, /json_pointer/)
  assert.match(structuredPreview, /line_start/)
  assert.match(structuredPreview, /scrollTargetWithin/)
})

test('review workbench constrains the viewport and keeps both columns independently scrollable', () => {
  assert.match(workbench, /class="document-review-page"/)
  assert.match(styles, /\.content:has\(\.document-review-page\)/)
  assert.match(styles, /height:\s*100dvh/)
  assert.match(styles, /padding:\s*12px 18px 16px/)
  assert.match(workbench, /grid-template-rows:minmax\(0,1fr\)/)
  assert.match(workbench, /\.chunk-pane\{[^}]*overflow-y:auto[^}]*overscroll-behavior:contain[^}]*scrollbar-gutter:stable/)
  assert.match(workbench, /class="chunk-toolbar"/)
  assert.match(workbench, /\.chunk-toolbar\{position:sticky;top:0/)
  assert.match(workbench, /\.complete\{position:sticky;bottom:0/)
  assert.match(preview, /grid-template-rows:minmax\(0,1fr\)/)
  assert.match(pdfPreview, /height:100%;min-height:0;overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable/)
  assert.match(docxPreview, /height:100%;min-height:0;overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable/)
  assert.doesNotMatch([preview, pdfPreview, docxPreview, structuredPreview].join('\n'), /height:720px/)
})

test('document replacement confirms historical activation and reports success accessibly', () => {
  assert.match(listing, /SOURCE_VERSION_REACTIVATION_REQUIRED/)
  assert.match(listing, /reactivateSourceVersion/)
  assert.match(listing, /未创建新版本/)
  assert.match(listing, /role="status" aria-live="polite"/)
  assert.match(listing, /\.json,.jsonl/)
})

test('review chrome is compact, metadata is folded and downloads remain in document management only', () => {
  assert.match(workbench, /class="review-header"/)
  assert.match(workbench, /<details ref="metaDetails" class="review-meta"/)
  assert.match(workbench, /分块信息 · r/)
  assert.match(workbench, /Source Preparation r/)
  assert.match(workbench, /Overlap/)
  assert.match(workbench, /当前生效/)
  assert.match(workbench, /候选/)
  assert.match(workbench, /keydown\.esc\.stop="closeMetaDetails"/)
  assert.match(workbench, /text-overflow:ellipsis/)
  assert.doesNotMatch(workbench, /<details[^>]*\sopen(?:\s|>)/)
  assert.doesNotMatch(workbench, /业务工作区 \/ 文档管理 \/ 文档审核/)
  assert.doesNotMatch(workbench, /panel summary/)
  assert.doesNotMatch(workbench, /sourceDownloadUrl|下载原文/)
  assert.doesNotMatch(preview, /sourceDownloadUrl|下载原文|原文证据|PDF 精确定位|DOCX 结构化定位/)
  assert.match(preview, /sourcePreviewUrl/)
})
