<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '../../api/platform'

const route = useRoute(), job = ref(null), candidates = ref([]), configs = ref([]), selectedTarget = ref('candidate_target'), error = ref(''), batch = ref(null)
const stages = ['uploaded','verified','contracts_metadata_imported','documents_objects_imported','waiting_for_milvus_configuration','waiting_for_milvus_verification','waiting_for_vector_capacity','ready_for_vector_import','importing_vectors','verified_vectors','assets_ready','route_candidates_ready','completed']
const currentIndex = computed(() => stages.indexOf(job.value?.stage))
async function load() { try { ;[job.value, candidates.value, configs.value] = await Promise.all([api.migrationJob(route.params.jobId), api.importedRouteCandidates(route.params.jobId), api.localMilvusConfigurations()]) } catch (e) { error.value = e.message } }
async function resume() { try { await api.resumeMigration(job.value.id, { selected_import_target: selectedTarget.value }); await load() } catch (e) { error.value = e.message } }
async function retry() { try { await api.retryMigration(job.value.id); await load() } catch (e) { error.value = e.message } }
async function activate(candidate) { try { await api.activateImportedRouteCandidate(candidate.id); await load() } catch (e) { error.value = e.message } }
async function activateAll() { try { batch.value = await api.activateReadyRouteCandidates(candidates.value.filter(item=>item.status==='ready').map(item=>item.id)); await load() } catch (e) { error.value = e.message } }
onMounted(load)
</script>
<template><section><div class="page-head"><div><h2>机构导入任务</h2><p><code>{{ job?.id }}</code> · 每个检查点可恢复，等待态不是失败。</p></div><span class="badge" :class="job?.status==='completed'?'green':job?.status==='failed'?'red':'amber'">{{ job?.status }}</span></div><section class="panel"><h3>导入检查点</h3><ol class="timeline"><li v-for="(stage,index) in stages" :key="stage" :class="{done:index<=currentIndex,failed:job?.status==='failed'&&index===currentIndex}"><b>{{ stage }}</b><span>{{ index<currentIndex?'已完成':index===currentIndex?'当前':'待执行' }}</span></li></ol><div v-if="job?.status==='waiting'" class="notice"><p>当前运行路由保持不变。补充并验证配置后可从此检查点继续。</p><label>向量导入目标<select v-model="selectedTarget"><option v-for="item in configs.filter(value=>['current_target','candidate_target'].includes(value.slot))" :key="item.slot" :value="item.slot">{{ item.slot }} · {{ item.status }} · {{ item.uri }}</option></select></label><button class="primary" @click="resume">继续导入</button></div><p v-if="job?.error" class="error">{{ job.error }}</p><button v-if="job?.status==='failed'" @click="retry">从最近检查点重试</button></section><section class="panel"><div class="panel-head"><div><h3>项目候选激活</h3><p>默认逐项目；“激活全部就绪项目”按顺序非原子执行。</p></div><button class="primary" :disabled="!candidates.some(item=>item.status==='ready')" @click="activateAll">激活全部就绪项目</button></div><table><thead><tr><th>ProjectDeployment</th><th>源 Route</th><th>资产</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in candidates" :key="item.id"><td>{{ item.project_deployment_id }}</td><td>v{{ item.source_route_version }}</td><td>{{ item.readiness.ready_asset_version_ids?.length||0 }}/{{ item.readiness.asset_version_ids?.length||0 }}</td><td><span class="badge" :class="item.status==='ready'||item.status==='activated'?'green':item.status==='failed'?'red':'amber'">{{ item.status }}</span></td><td><button v-if="['ready','failed'].includes(item.status)" @click="activate(item)">激活此项目</button></td></tr></tbody></table><pre v-if="batch">{{ JSON.stringify(batch,null,2) }}</pre></section><p v-if="error" class="error">{{ error }}</p></section></template>
