<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { api } from '../../api/platform'
import { fallbackSinkIds, presentStage, presentStatus, shortTechnicalId } from './jobPresentation'

const jobs = ref([]), selectedJobs = ref([]), error = ref(''), logs = ref([]), generations = ref([]), logJobId = ref(''), logLoading = ref(false), logError = ref(''), copyNotice = ref('')
let refreshTimer = null, loading = false, disposed = false
const selectedJob = computed(() => jobs.value.find(item => item.id === logJobId.value))
async function load() { if (refreshTimer) { clearTimeout(refreshTimer); refreshTimer = null }; if (loading) return; loading = true; try { jobs.value = await api.knowledgeJobs(); error.value = '' } catch (err) { error.value = err.message } finally { loading = false; scheduleRefresh() } }
function scheduleRefresh() { if (refreshTimer) clearTimeout(refreshTimer); refreshTimer = !disposed && jobs.value.some(job => ['queued', 'running'].includes(job.status)) ? setTimeout(load, 3000) : null }
async function action(action, ids = selectedJobs.value) { if (!ids.length) return; try { await api.manageKnowledgeJobs({ job_ids: ids, action }); selectedJobs.value = []; await load() } catch (err) { error.value = err.message } }
async function showLogs(id) { if (logJobId.value === id) { logJobId.value = ''; return }; logJobId.value = id; logs.value = []; generations.value = []; logError.value = ''; logLoading.value = true; try { [logs.value, generations.value] = await Promise.all([api.knowledgeJobLogs(id), api.knowledgeJobChunkGenerations(id, true)]) } catch (err) { logError.value = err.message } finally { logLoading.value = false } }
async function copyId(id) { try { await navigator.clipboard?.writeText(id); copyNotice.value = '已复制完整 ID'; setTimeout(() => { copyNotice.value = '' }, 1800) } catch { copyNotice.value = '浏览器不支持复制，请手动选择' } }
onMounted(load); onBeforeUnmount(() => { disposed = true; if (refreshTimer) clearTimeout(refreshTimer) })
</script>

<template>
  <section><div class="page-head"><div><h2>处理任务</h2><p>任务由文档库模板绑定自动创建；本页用于监控、日志和失败恢复。全失败的空结果库进入清理后，请返回文档库重新发起处理。</p></div><div class="page-actions"><button @click="action('retry')">重试失败分块</button><button class="danger" @click="action('delete')">批量删除</button></div></div><div class="actions"><button class="danger" @click="action('cancel')">批量停止</button><span class="badge amber">选择任务后执行批量操作</span><span v-if="copyNotice" class="copy-notice">{{ copyNotice }}</span></div><p v-if="error" class="error">{{ error }}</p><div class="table-wrap"><table><thead><tr><th>选择</th><th>任务</th><th>目标知识库</th><th>当前阶段</th><th>进度</th><th>状态</th><th>操作</th></tr></thead><tbody><template v-for="job in jobs" :key="job.id"><tr><td><input v-model="selectedJobs" type="checkbox" :value="job.id"></td><td><b>{{ job.template?.name || '知识生产任务' }}</b><button class="technical-id" :title="job.id" @click="copyId(job.id)">{{ shortTechnicalId(job.id) }} · 点击复制</button><small>{{ new Date(job.created_at).toLocaleString() }}</small></td><td><div v-if="job.sink_libraries?.length" class="sink-list"><span v-for="library in job.sink_libraries" :key="library.id"><b>{{ library.name }}</b><small>{{ library.graph_mode || library.knowledge_type }}</small></span></div><div v-else class="sink-list unavailable"><span v-for="libraryId in fallbackSinkIds(job)" :key="libraryId"><b>已不可用</b><small :title="libraryId">{{ shortTechnicalId(libraryId) }}</small></span></div></td><td>{{ presentStage(job.stage) }}</td><td><div class="job-progress" :aria-label="`任务进度 ${job.progress?.percent || 0}%`"><i :style="{ width: `${job.progress?.percent || 0}%` }"></i></div><small>{{ job.progress?.percent || 0 }}%<template v-if="job.progress?.total_nodes"> · {{ job.progress.completed_nodes }}/{{ job.progress.total_nodes }} 节点</template></small></td><td><span :class="['badge', presentStatus(job.status).tone]">{{ presentStatus(job.status).label }}</span><small v-if="job.failed_chunk_count">{{ job.failed_chunk_count }} 个分块失败，可重试</small></td><td><button :aria-expanded="logJobId === job.id" @click="showLogs(job.id)">{{ logJobId === job.id ? '收起' : '日志' }}</button></td></tr><tr v-if="logJobId === job.id" class="job-log-row"><td colspan="7"><div class="job-log-panel"><h4>任务日志：{{ selectedJob?.template?.name || shortTechnicalId(job.id) }}</h4><p v-if="logLoading">正在加载日志…</p><p v-else-if="logError" class="error">{{ logError }}</p><template v-else><pre v-if="logs.length">{{ JSON.stringify(logs, null, 2) }}</pre><p v-else>暂无审计日志。</p><section v-if="generations.length"><h4>失败分块</h4><div class="table-wrap"><table><thead><tr><th>知识类型</th><th>来源版本</th><th>分块</th><th>尝试</th><th>错误</th></tr></thead><tbody><tr v-for="item in generations" :key="item.id"><td>{{ item.knowledge_type }}</td><td>{{ item.source_version_id }}</td><td>#{{ item.chunk_index }}</td><td>{{ item.attempt_count }}</td><td>{{ item.error }}</td></tr></tbody></table></div></section></template></div></td></tr></template></tbody></table></div>
  </section>
</template>

<style scoped>
.copy-notice{color:var(--green);font-size:13px;font-weight:700}.technical-id{display:block;min-height:0;margin-top:5px;padding:0;border:0;color:var(--muted);background:transparent;font-size:12px;font-weight:600}.sink-list{display:grid;gap:7px}.sink-list span{display:grid;gap:2px}.sink-list b{font-size:14px}.sink-list small{color:var(--muted);font-size:12px}.sink-list.unavailable b{color:var(--amber)}.job-progress{width:170px;max-width:100%;height:8px;overflow:hidden;margin-bottom:6px;border-radius:999px;background:#e8edf5}.job-progress i{display:block;height:100%;border-radius:inherit;background:var(--blue);transition:width .25s ease}.job-log-row>td{padding:0 14px 16px;background:var(--panel-muted)}.job-log-panel{padding:18px;border:1px solid var(--border);border-radius:12px;background:#fff}.job-log-panel h4{margin:0 0 12px;font-size:16px}.job-log-panel pre{max-height:320px;overflow:auto;margin:0 0 16px}
</style>
