<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../../api/platform'
const instance=ref(null),health=ref(null),configs=ref([]),error=ref(''),notice=ref(''),uri=ref(''),username=ref(''),secret=ref(''),tls=ref(false)
const candidate=computed(()=>configs.value.find(item=>item.slot==='candidate_target')),current=computed(()=>configs.value.find(item=>item.slot==='current_target'))
const component=key=>health.value?.components?.find(item=>item.component===key)
const steps=computed(()=>[['管理员认证',true],['导入 deployment_seed',instance.value?.initialized],['机构身份锁定',instance.value?.initialized],['MySQL / MinIO 检查',component('mysql')?.status==='healthy'&&component('minio')?.status==='healthy'],['Milvus / Embedding / LLM',candidate.value?.status==='verified'||current.value?.status==='verified'],['Worker / Runner / 解析与磁盘',component('disk')?.status==='healthy'&&component('worker')?.status==='healthy'&&component('runner')?.status==='healthy'],['向量导入与验证',instance.value?.initialized],['进入项目候选激活',instance.value?.initialized]])
async function load(){try{;[instance.value,health.value,configs.value]=await Promise.all([api.instance(),api.observabilityComponents(),api.localMilvusConfigurations()]);const value=candidate.value||current.value;if(value){uri.value=value.uri;username.value=value.username||'';tls.value=value.tls_enabled}}catch(e){error.value=e.message}}
async function saveCandidate(){try{await api.putLocalMilvusConfiguration('candidate_target',{uri:uri.value,username:username.value||null,secret:secret.value||null,tls_enabled:tls.value,database_name:'default',preserve_secret:!secret.value});secret.value='';notice.value='候选配置已保存。';await load()}catch(e){error.value=e.message}}
async function verifyCandidate(){try{await api.verifyLocalMilvusConfiguration('candidate_target');notice.value='候选 Milvus 验证通过。';await load()}catch(e){error.value=e.message}}
async function promote(){try{await api.promoteLocalMilvusCandidate();notice.value='候选目标已切换为 current。';await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section><div class="page-head"><div><h2>机构本地初始化</h2><p>组件状态复用工作台手动检查结果；打开页面不会触发外部探针。</p></div><span class="badge blue">{{ instance?.display_name }}</span></div><div class="grid2"><section class="panel"><h3>初始化步骤</h3><ol class="timeline"><li v-for="([label,done],index) in steps" :key="label" :class="{done}"><b>{{ index+1 }}. {{ label }}</b><span class="badge" :class="done?'green':'amber'">{{ done?'通过':'待完成' }}</span></li></ol></section><section class="panel stack"><h3>Milvus 候选目标</h3><p>Current：<code>{{ current?.uri||'未配置' }}</code></p><label>Candidate URI<input v-model="uri"></label><label>用户名<input v-model="username"></label><label>密码 / Token<input v-model="secret" type="password"></label><label><input v-model="tls" type="checkbox"> 启用 TLS</label><div class="actions"><button @click="saveCandidate">保存候选</button><button class="success" :disabled="!candidate" @click="verifyCandidate">验证</button><button class="primary" :disabled="candidate?.status!=='verified'" @click="promote">切换为 Current</button></div></section></div><section class="panel"><h3>组件健康</h3><div class="card-grid"><div v-for="value in health?.components" :key="value.component" class="stat-card"><small>{{ value.label }}</small><b>{{ value.status }}</b><span>{{ value.summary }}</span></div></div></section><p v-if="notice" class="notice">{{ notice }}</p><p v-if="error" class="error">{{ error }}</p></section></template>
