<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../../api/platform'
const instance=ref(null),health=ref(null),configs=ref([]),error=ref(''),notice=ref(''),uri=ref(''),token=ref(''),verifying=ref(false)
const candidate=computed(()=>configs.value.find(item=>item.slot==='candidate_target')),current=computed(()=>configs.value.find(item=>item.slot==='current_target'))
const component=key=>health.value?.components?.find(item=>item.component===key)
const steps=computed(()=>[['管理员认证',true],['导入 deployment_seed',instance.value?.initialized],['机构身份锁定',instance.value?.initialized],['MySQL / MinIO 检查',component('mysql')?.status==='healthy'&&component('minio')?.status==='healthy'],['Milvus / Embedding / LLM',candidate.value?.status==='verified'||current.value?.status==='verified'],['Worker / Runner / 解析与磁盘',component('disk')?.status==='healthy'&&component('worker')?.status==='healthy'&&component('runner')?.status==='healthy'],['向量导入与验证',instance.value?.initialized],['进入项目候选激活',instance.value?.initialized]])
async function load(){try{;[instance.value,health.value,configs.value]=await Promise.all([api.instance(),api.observabilityComponents(),api.localMilvusConfigurations()]);const value=candidate.value||current.value;if(value)uri.value=value.uri}catch(e){error.value=e.message}}
async function saveCandidate(){verifying.value=true;error.value='';notice.value='';try{const value=await api.putLocalMilvusConfiguration('candidate_target',{uri:uri.value,token:token.value||null,preserve_token:!token.value});token.value='';await load();if(value.status==='verified')notice.value='Milvus 连接通过，候选服务已注册。';else error.value=value.verification_error||'Milvus 连接失败，请修正配置后重试。'}catch(e){error.value=e.message}finally{verifying.value=false}}
async function promote(){try{await api.promoteLocalMilvusCandidate();notice.value='候选目标已切换为 current。';await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section><div class="page-head"><div><h2>机构本地初始化</h2><p>机构 Milvus 仅保存在本地；保存 URI/Token 后自动执行真实连接测试。</p></div><span class="badge blue">{{ instance?.display_name }}</span></div><div class="grid2"><section class="panel"><h3>初始化步骤</h3><ol class="timeline"><li v-for="([label,done],index) in steps" :key="label" :class="{done}"><b>{{ index+1 }}. {{ label }}</b><span class="badge" :class="done?'green':'amber'">{{ done?'通过':'待完成' }}</span></li></ol></section><section class="panel stack"><h3>注册 Milvus 服务</h3><p>Current：<code>{{ current?.uri||'未配置' }}</code> <span v-if="current?.status==='verified'" class="badge green">连接通过</span><small v-if="current"> · {{ current.token_configured?'Token 已配置':'无 Token' }}</small></p><label>Candidate URI<input v-model="uri" required placeholder="http://milvus:19531"></label><label>Token（可选，留空保留）<input v-model="token" type="password" autocomplete="new-password"></label><p v-if="candidate?.status==='verification_failed'" class="error">{{ candidate.verification_error||'连接失败' }}</p><p v-else-if="candidate?.status==='verified'" class="notice">Candidate 连接通过，可以切换为 Current。</p><div class="actions"><button :disabled="verifying" @click="saveCandidate">{{ verifying?'正在连接验证…':'保存并验证' }}</button><button class="primary" :disabled="candidate?.status!=='verified'||verifying" @click="promote">切换为 Current</button></div></section></div><section class="panel"><h3>组件健康</h3><div class="card-grid"><div v-for="value in health?.components" :key="value.component" class="stat-card"><small>{{ value.label }}</small><b>{{ value.status }}</b><span>{{ value.summary }}</span></div></div></section><p v-if="notice" class="notice">{{ notice }}</p><p v-if="error" class="error">{{ error }}</p></section></template>
