import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const registry = fs.readFileSync(new URL('./MilvusTargetRegistryView.vue', import.meta.url), 'utf8')
const initialization = fs.readFileSync(new URL('./LocalInitializationView.vue', import.meta.url), 'utf8')
const publishing = fs.readFileSync(new URL('./ProjectAuthorizationView.vue', import.meta.url), 'utf8')
const institution = fs.readFileSync(new URL('./InstitutionDeploymentView.vue', import.meta.url), 'utf8')
const api = fs.readFileSync(new URL('../../api/platform.js', import.meta.url), 'utf8')

test('central Milvus registry creates, verifies, edits and exposes only verified binding options', () => {
  assert.match(registry, /api\.createMilvusTarget/)
  assert.match(registry, /api\.patchMilvusTarget/)
  assert.match(registry, /api\.verifyMilvusTarget/)
  assert.match(registry, /api\.checkMilvusTargetHealth/)
  assert.match(registry, /api\.checkMilvusTargetCollections/)
  assert.match(registry, /api\.putAuthoringMilvusTarget/)
  assert.match(registry, /token_configured/)
  assert.doesNotMatch(registry, /databaseName|tls_enabled|username/)
  assert.match(registry, /正在连接验证/)
  assert.match(registry, /候选地址连接失败/)
  assert.match(registry, /新地址验证通过后不会自动切换/)
  assert.match(registry, /当前健康/)
  assert.match(registry, /启动 30 秒后自动检查连接/)
  assert.match(registry, /检查当前连接/)
  assert.match(registry, /检查 Collection/)
  assert.match(registry, /\.status-stack \.badge\{justify-self:start\}/)
  assert.match(registry, /验证候选/)
  assert.match(registry, /默认知识写入目标/)
  assert.match(registry, /设为默认写入/)
  assert.doesNotMatch(registry, /知识生产服务/)
  assert.match(registry, /onMounted\(load\)/)
  assert.doesNotMatch(registry, /onMounted\(checkHealth/)
  assert.match(api, /milvusTargets:.*\/api\/milvus-targets/)
  assert.match(api, /checkMilvusTargetHealth:.*\/health-check/)
  assert.match(api, /checkMilvusTargetCollections:.*\/collections-check/)
  assert.match(publishing, /verifiedMilvusTargets/)
  assert.match(publishing, /milvus_target_id: target\.id/)
  assert.match(publishing, /milvus_target_revision_id: revision\.id/)
  assert.doesNotMatch(api, /createDeployment:|patchDeployment:|migrationPlan:|exportMigration:/)
})

test('institution Milvus remains local and candidate save automatically verifies', () => {
  assert.match(institution, /机构 Milvus 由 local 初始化配置/)
  assert.match(initialization, /环境变量建议地址，尚未保存或验证/)
  assert.doesNotMatch(publishing, /saveInstitutionTarget/)
  assert.match(initialization, /注册 Milvus 服务/)
  assert.match(initialization, /保存并验证/)
  assert.doesNotMatch(initialization, /verifyCandidate/)
  assert.match(initialization, /candidate\?\.status==='verification_failed'/)
})
